services:
  - type: web
    name: resume-helper-api
    env: ubuntu
    rootDir: resume_helper_backend
    buildCommand: |
      apt-get update && apt-get install -y python3 python3-pip libreoffice
      pip3 install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: B2_KEY_ID
        sync: false
      - key: B2_APPLICATION_KEY
        sync: false
      - key: B2_BUCKET_NAME
        sync: false
      - key: B2_ENDPOINT
        sync: false