services:
  - type: web
    name: resume-helper-api
    env: docker
    rootDir: resume_helper_backend
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 2 app:app
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: B2_KEY_ID
        sync: false
      - key: B2_APPLICATION_KEY
        sync: false
      - key: B2_BUCKET_NAME
        sync: false
      - key: B2_ENDPOINT
        sync: false